channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - conda-forge::pytorch-lightning
  - conda-forge::transformers
  - pytorch::pytorch
  - pandas
  - conda-forge::spacy
  - executing
  - ca-certificates
  - jupyter_core
  - jedi
  - ncurses
  - python-dateutil
  - stack_data
  - ptyprocess
  - six
  - pyparsing
  - setuptools
  - jupyter_client
  - pure_eval
  - parso
  - sqlite
  - xz
  - zeromq
  - psutil
  - asttokens
  - pygments
  - appnope
  - traitlets
  - wcwidth
  - tornado
  - libcxx
  - libsodium
  - zlib
  - pyzmq
  - prompt-toolkit
  - decorator
  - matplotlib-inline
  - pip
  - libffi
  - debugpy
  - entrypoints
  - openssl
  - readline
  - ipython
  - wheel
  - nest-asyncio
  - backcall
  - pickleshare
  - pexpect
  - packaging
  - certifi
  - tk
  - ipykernel
  - jupyter
  - ipywidgets
  - matplotlib
  - pip:
    - tensorboard
    - seqeval
prefix: /opt/miniconda3/envs/nertag_env
